### ISSUE TITLE
Bigsearch doesn't cope with large resultsets, which is ironic

### ISSUE THREAD

**Issue by Benthem** [PennyDreadfulMTG/Penny-Dreadful-Tools#129]
query for example:

!bigsearch f:pd t:dragon

No further action after 'sending you a PM'

When writing this query in a PM there is zero response.

**Comment by Benthem** [comment]
Queries that have the same result:

!bigsearch f:pd t:goblin
!bigsearch f:pd o:the
!bigsearch t:dragon

**Comment by bakert** [comment]
Bot says:

```
discord.errors.HTTPException: BAD REQUEST (status code: 400)
```

The message is too long for Discord to accept. We could probably just chunk it.

**Comment by bakert** [comment]
<img width="1099" alt="screen shot 2016-10-10 at 10 30 51 am" src="https://cloud.githubusercontent.com/assets/1541/19231932/ba6c6ad2-8ed4-11e6-86fc-f2d741beb184.png">

The cure might be worse than the disease here. Maybe we should say "N results, not even going to PM you because that's a lot of results"?

Code that makes post_cards send arbitrary-length messages is:

```
diff --git a/bot.py b/bot.py
index 115a154..4e00775 100644
--- a/bot.py
+++ b/bot.py
@@ -1,3 +1,5 @@
+import textwrap
+
 import discord

 import command
@@ -63,6 +65,14 @@ class Bot:
                 text += 'No image available.'
         text += '\n' + additional_text
         if image_file is None:
-            await self.client.send_message(channel, text)
+            await self.chunk_send(channel, text)
         else:
-            await self.client.send_file(channel, image_file, content=text)
+            await self.chunk_send(channel, text, image_file)
+
+    async def chunk_send(self, channel, text, file=None):
+        print(text)
+        msgs = textwrap.wrap(text, 2000)
+        if file:
+            await self.client.send_file(channel, image_file, content=msgs.pop(0))
+        for msg in msgs:
+            await self.client.send_message(channel, msgs.pop(0))
```

**Comment by bakert** [comment]
So I pushed b52e204 which stops the bot telling you it's going to PM you and then not doing it. (Note: may be edge cases with long names close to 100 cards where this is not true, I didn't go for perfection.) It doesn't do anything particularly useful but at least it doesn't lie to you.

I'm not sure what the right behavior is here. bigsearch is basically a massively worse magidex. It's main use is for when magidex has the wrong legality. And we're sure to have that for a few days or at least hours at the next rotation too. I'd prefer to make our own magidex than have the bot send you 50+ PMs. But we don't particularly want to make our own magidex when we have magidex.

@binarySwordsman – How is our relationship with /u/basicer?. I feel like if we got them to agree to update the legality swiftly after the rotation we could just _drop_ bigsearch altogether and the current search functionality and link to magidex would always suffice.

**Comment by bakert** [comment]
I've unilaterally killed !bigsearch because it doesn't work on big searches and requires an otherwise unused param to bot.post_cards.

I think we still need a plan for rotation if we aren't going to have magidex update instantly but !bigsearch isn't it, IMHO.

Pretty easy to reinstate if people hate this decision.
