### ISSUE TITLE
I can not sign up for league with SQL errors.

### ISSUE THREAD

**Issue by 4643893** [PennyDreadfulMTG/Penny-Dreadful-Tools#1417]
I can not sign up for league with SQL errors.
Error Code: 1292. Truncated incorrect DOUBLE  #value
Probabｌy because My user name is only number.
I'm sorry for my poor English.

**Comment by silasary** [comment]
Yes, something is probably attempting to treat your username as a number, rather than a string.

I'll look into it for you 😃

**Comment by bakert** [comment]
Our `sqlescape` code thinks it is smart and inspects the value it is given and if it's a number it doesn't quote it. This is what causes the issue here. This lets us set up the card db and other things with some pretty generic handling.

In this case, and plenty of other cases I'm sure, we'd rather be explicit than rely on inspecting the variable to determine type.

I'm actually inclined to special case the version that inspects the value and make `sqlescape` generally just escape strings.

**Comment by bakert** [comment]
Hm, no, I guess it's the case that we want to pass anything that has ever been user input through this even if it's meant to be a number so that's not quite right.

I'm going to fix this in this specific case with a force_string param and wait for this to bite us again before I do anything else :P @4643893 you are our guinea pig :P please let us know what breaks!

**Comment by bakert** [comment]
b8390d75.
