### ISSUE TITLE
Normalize deck colour names without mangling the user specified colour

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/Penny-Dreadful-Tools#1944]
Gatherling 
http://gatherling.com/deck.php?mode=view&id=52814

Name Changed
https://pennydreadfulmagic.com/decks/5798/

**Comment by bakert** [comment]
This is intentional behavior based on the colors used in the deck. I'd say that the manabase being GB makes this a bug but the manabase can actually pretty handily cast spells of all five colors.

The intent of this code is to make every GB and BG into "Golgari" rather than to overrule the deck creator on what colors their deck is, though. Possibly we should only normalize color names to their equivalent normalization rather than inspecting the cards for colors and overruling.

**Comment by bakert** [comment]
One problem here is that only rarely will they use precisely what we are looking for. Golgari is one of those cases but BG/GB is not. That said if they use a keyword that we recognize like Golgari we could still refuse to replace it with something else. This opens the door to lying about your decks colors in the name but that doesn't seem like a major concern as we have the color bar.

**Comment by bakert** [comment]
![image](https://user-images.githubusercontent.com/1541/39816251-9daeabf6-5392-11e8-91d6-4a574a56a6aa.png)

This has come up enough times that it's no longer a question of whether we should do it only when.

**Comment by bakert** [comment]
7e2474d.
