### ISSUE TITLE
Some of our queries don't work with ONLY_FULL_GROUP_BY which is on by default from mysql 5.7.5 onwards

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#3804]
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

`INSERT INTO legality` and probably the new head to head stuff getting mtgo_username and probably a bunch of others.

**Comment by bakert** [comment]
ok, the config change did the trick, at least as far as getting the cards imported
[mysqld]
sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

**Comment by bakert** [comment]
I don't think we should insist on devs/hosts configuring mysql a non-default way so our options here are:

(1) Change the queries so they don't select these fields.
(2) Add ANY_VALUE() around the columns we "know" are going to be unique.
(3) Add the columns we are SELECT-ing to the GROUP BY clause.

I'll do (3) if there's no perf penalty. Otherwise (2).

It's kind of frustrating that MySQL can't understand that a UNIQUE constraint means that if we SELECT from a table using its primary key the other column is guaranteed to be unique. I'll have a play around and see what's what.

**Comment by Pseudodude** [comment]
There's also option 4 of excluding ONLY_FULL_GROUP_BY from sql-mode at runtime, via something like this (which isn't perfect because it leaves a leading comma):

SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

Supposedly ONLY_FULL_GROUP_BY was changed to be true by default because it had been improved to [recognize when queries should be deterministic.](http://mysqlserverteam.com/mysql-5-7-only_full_group_by-improved-recognizing-functional-dependencies-enabled-by-default/), so if we're seeing this error it might be an indication that the queries aren't completely watertight.

**Comment by bakert** [comment]
Yeah I think you may be right that this is going to expose real issues and will actually understand things like the UNIQUE constraint when joining on primary key, etc.

Logged #3811 for the first problem which is an actual bug.

**Comment by bakert** [comment]
Apart from #3811 which has its own ticket I only found one of these and fixed it in 1362d13. It seems MySQL is smart enough to derive where these things are ok apart from in the particular case of archetypes only having one ancestor with depth=1 in archetype_closure which is enforced in code rather than in the db.

Closing this as no known issues not covered by other tickets. I'm using 5.7 on local now so I'm sure I'll find any I've missed in due course.
