### ISSUE TITLE
Decksite displays ugnly scroll bars

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#3963]
Firefox, Windows 10.
![image](https://user-images.githubusercontent.com/194254/34647941-669f4dae-f3e4-11e7-839b-58b673eaa199.png)

**Comment by bakert** [comment]
Gross. This because of `overflow-x: scroll` on &lt;section&gt; which is *also* clipping the left-hand margin. So I'm going to have to find some other solution to "tables that do not have mobile treatment extend into the right margin" although the solution can't be to give them the mobile treatment in some cases because the tables are too large and it makes the page very slow. I will ponder.

**Comment by bakert** [comment]
f6f9a088.
