### ISSUE TITLE
Gatherling test is so slow I had to remove it let build process work

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#4487]
Should fix not remove.

**Comment by silasary** [comment]
@jgabrielygalan found the source of this on Discord last night.

**Comment by jgabrielygalan** [comment]
did I? Actually, after reading this comment, thinking about what I said yesterday, I came to the conclusion that since the current code is not able to recover a partially scraped tournament, we should short circuit and skip the tournament if it's found in the competition table. That would be a huge optimization since it won't try to scrape all decks. What do you think?
