### ISSUE TITLE
Hide Illegal decks by default

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#457]
Currently, if someone posts an illegal deck, or one gets bumped back into view, It shows up on the main page.

There is no obvious sign it's illegal until you go into the deck view.

We need to either Hide it, or indicate that it's illegal.

**Comment by silasary** [comment]
My personal preference is to add Set Symbols showing which seasons the deck is legal for.
This would require #458 to be implemented.

**Comment by silasary** [comment]
Something like this:  
![mockup](https://cloud.githubusercontent.com/assets/194254/19918287/02b8d37e-a11e-11e6-997a-519a62e155c7.PNG)

Set Symbols care of https://andrewgioia.github.io/Keyrune/

**Comment by bakert** [comment]
That font is very nice. I wonder if a big [1], [2] graphic is more comprehensible though? Either one would be good.

**Comment by silasary** [comment]
Yeah, we can change the size easily enough.
That screenshot was a minimum viable mockup

**Comment by bakert** [comment]
It wasn't really the size so much as just ... do people link the seasons with the sets that clearly in their minds? I know I don't. There aren't any legal KLD cards.

**Comment by silasary** [comment]
True.  I'd much rather call S1=SOI, and S2=EMN
But that's what @binarySwordsman codified the seasons as, so we either need to retroactively change the names at source, transform the names after we import legality lists, or find another way of signifying seasons.

**Comment by silasary** [comment]
That said, most people don't have [EMN_legal_cards.txt](http://pdmtgo.com/EMN_legal_cards.txt) on their mind, so both of the first two are probably fine.

**Comment by bakert** [comment]
EMN for the current season definitely leaves a lot of room for confusion, too, esp as you say some things are standardized the other way.

As boring as it is I think maybe just a big stylized "1", "2", etc. might be clearest. We can experiment.

**Comment by binarySwordsman** [comment]
This is currently KLD season if you're thinking of classifying it that way.

**Comment by bakert** [comment]
Defining what is a current season deck is actually kind of interesting.

If you make a deck now what happens to be legal again in two seasons time should it suddenly show up again on lists and in stats? Probably not. Especially not stats on who it beat and so on.

Then again if you make a deck on tapped out and update it across multiple seasons it should show as current.

So I think bizarrely enough that `updated_date` (not legality and not created date) is the best guide we have to "things to show by default". For tournament and league decks this will forever be the same as created date and one day we may update based on tapped out. It does mean some decks people made that ARE legal will be HIDDEN by default because they are from a past time. But that should be rare and I think it's ok.

**Comment by bakert** [comment]
This relies on us picking up a "real" updated_date from Tapped Out which I don't think we are currently doing? I don't see a tapped out API key in the config.json on prod. @silasary – is there meant to be?

**Comment by bakert** [comment]
Relatedly, does anyone know how you get a Tapped Out API key? :)

**Comment by bakert** [comment]
def season_query():
    return '(d.updated_date > {rotation})'.format(rotation=dtutil.dt2ts(rotation.last_rotation()))

**Comment by silasary** [comment]
I know how to get a key.  But no clue how to use it.

The documentation on the TappedOut API is pretty useless.

**Comment by silasary** [comment]
That's why we're using user/pass, and authenticating via Cookie.

**Comment by bakert** [comment]
I think we're happy with the current state of affairs now that it's clear in all views whether a deck is legal or not.
