### ISSUE TITLE
Variety achievement does not insist you finish your run but says it does

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#5752]
brian1234 has it for s10 for example.

**Comment by adambiltcliffe** [comment]
He had complete league runs with Tempered Steel, White Weenie and Affinity due to categorisation errors. I've just retagged them but will have to wait for the preaggregation job to run to check if he still has the achievement. Have you seen any other examples?

I'm pretty sure that the existing query should cover this:

`CASE WHEN COUNT(DISTINCT CASE WHEN dc.wins + dc.losses >= 5 AND ct.name = 'League' THEN d.archetype_id ELSE NULL END) >= 3 THEN True ELSE False END`

**Comment by bakert** [comment]
Sounds like you nailed it.
