### ISSUE TITLE
!rotation command that gives time to/date of rotation and possibly other details

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#85]

**Comment by bakert** [comment]
<img width="507" alt="screen shot 2016-09-30 at 11 32 05 am" src="https://cloud.githubusercontent.com/assets/1541/18989012/8daea1f2-8701-11e6-8930-ddac12635599.png">

**Comment by silasary** [comment]
Yeah, someone else asked about it this morning as well.

**Comment by silasary** [comment]
Depends on #15

**Comment by silasary** [comment]
Ideal Implementation: (Because there's no API for "When does the next set get released?")
Check database for latest set with type 'Expansion'
If that set has a release date in the future (mtgjson puts a new set up when full spoiler is released, ~two weeks before release date), then list time until that release.  
Otherwise, give an error message saying rotation is too far away to worry about.

**Comment by silasary** [comment]
Note that while looking for APIs, I the closest I could find was http://whatsinstandard.com, which is good for every second PD rotation, but wouldn't help us for mid-block sets, like `EMN` or `AER`  (Woah, that's a weird code)

**Comment by bakert** [comment]
The future name and release date of sets is known information and a Google search will usually position it at the top in some way. My ruby prog that generates the proxies site just has it all hardcoded. That's not ideal but if we can hardcode "Bob" and "Tim" we can probably hardcode that somewhere? Shame that mtgjson doesn't include known future sets with empty cards array.

**Comment by silasary** [comment]
I'll send a feature request their way with that.
